### ISSUE TITLE
chef-server-ctl 12.18.14 list-client-keys command not working

### ISSUE THREAD

**Issue by jeremymv2** [chef-customers/dockerized-chef-services#22]
The following issue exists with:
```
chef_server_docker_origin = "chefserverofficial"
chef_server_version = "12.18.14"
```

```
~ $ chef-server-ctl list-client-keys bob
bundler: failed to load command: binstubs/chef-server-ctl (binstubs/chef-server-ctl)
Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/opscode/pivotal.rb
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/vendor/bundle/ruby/2.5.0/gems/mixlib-config-2.2.13/lib/mixlib/config.rb:63:in `read'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/vendor/bundle/ruby/2.5.0/gems/mixlib-config-2.2.13/lib/mixlib/config.rb:63:in `from_file'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/omnibus-ctl/lib/chef_server_ctl/helpers/key_ctl_helper.rb:8:in `initialize'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/omnibus-ctl/plugins/key_control.rb:166:in `new'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/omnibus-ctl/plugins/key_control.rb:166:in `block in load_file'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/vendor/bundle/ruby/2.5.0/bundler/gems/omnibus-ctl-e160156deaa0/lib/omnibus-ctl.rb:204:in `block in add_command_under_category'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/vendor/bundle/ruby/2.5.0/bundler/gems/omnibus-ctl-e160156deaa0/lib/omnibus-ctl.rb:747:in `run'
  /hab/pkgs/jeremymv2/chef-server-ctl/12.18.14/20181017194418/omnibus-ctl/bin/chef-server-ctl:254:in `<top (required)>'
  binstubs/chef-server-ctl:29:in `load'
  binstubs/chef-server-ctl:29:in `<top (required)>'
~ $
```

**Comment by jeremymv2** [comment]
The fix appears to be in https://github.com/chef/chef-server/pull/1573 which ended up in `12.19.26`. However, those Chef Server docker containers do not appear to be working with this repo and will require some investigation and analysis.

⚠️ That analysis must be completed in order to support client upgrades of the Chef Server from `12.18.14`.
